//
//  StyleKit.m
//  Glamify
//
//  Created by Brandon Shega on 12/16/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKit.h"


@implementation StyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1WithFrame: (CGRect)frame;
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* gradientColor = [UIColor colorWithRed: 1 green: 0.799 blue: 0.909 alpha: 1];

    //// Gradient Declarations
    CGFloat gradientLocations[] = {0, 1};
    CGGradientRef gradient = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)UIColor.whiteColor.CGColor, (id)gradientColor.CGColor], gradientLocations);

    //// Rectangle Drawing
    CGRect rectangleRect = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.02000 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.06667 + 0.5), floor(CGRectGetWidth(frame) * 0.98000 + 0.5) - floor(CGRectGetWidth(frame) * 0.02000 + 0.5), floor(CGRectGetHeight(frame) * 0.93333 + 0.5) - floor(CGRectGetHeight(frame) * 0.06667 + 0.5));
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: rectangleRect cornerRadius: 5];
    CGContextSaveGState(context);
    [rectanglePath addClip];
    CGContextDrawLinearGradient(context, gradient,
        CGPointMake(CGRectGetMidX(rectangleRect), CGRectGetMinY(rectangleRect)),
        CGPointMake(CGRectGetMidX(rectangleRect), CGRectGetMaxY(rectangleRect)),
        0);
    CGContextRestoreGState(context);
    [gradientColor setStroke];
    rectanglePath.lineWidth = 0.2;
    [rectanglePath stroke];


    //// Cleanup
    CGGradientRelease(gradient);
    CGColorSpaceRelease(colorSpace);
}

@end
